config/routes.rb
ICAPresents::Application.routes.draw do
  
  resources :home

  resources :sessions

  resources :projects

  resources :messages

  resources :votes

  resources :editions

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/identity/callback', to: 'sessions#create', as: 'admin_signin'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'my_votes', to: 'votes#show', as: 'my_votes'

  root 'home#index'

  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :teacher

  validates_presence_of :content, message: 'Can not be empty'
  validates_length_of :content, maximum: 255, message: 'Can not be longer than 255 characters'
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html, :json
  before_action :check_admin, except: [:index]

  def index
    if params[:latest]
      @messages = Message.where('id > ?', params[:latest]).order('id DESC')
    else
      @messages = Message.all.order('id DESC')
    end
    respond_with @messages
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.teacher = current_user
    if @message.save
      redirect_to messages_path, notice: 'The message has been added.'
    else
      render action: 'new'
    end
  end

  def destroy
    @message = Message.where(id: params[:id]).first
    if @message.destroy
      redirect_to messages_path, notice: 'The message has been deleted.'
    else
      redirect_to messages_path, notice: 'The message could not be added.'
    end
  end

  private
    def check_admin
      unless admin?
        redirect_to root_url, notice: 'Only administrators have access.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params[:message].permit(:content)
    end
end

app/views/messages/index.html.erb
<% if @messages.empty? %>
<div class="row project-item">
  <p class="top">No news messages found.</p>
</div>
<% end %>
<% @messages.each do |message| %>
<div class="row project-item">
  <h2>News message</h2>
  <p class="left">
  <%= message.content %>  
  </p>
  <% if admin? %>
  <%= link_to raw('<i class="large icon-remove"></i>'), message_path(message), method: :delete, data: { confirm: 'Are you sure you want to delete this news message?' }, class: 'button right no-styling', style: 'width: 50px; margin-right: 50px;' %>
  <% end %>
</div>
<% end %>

app/views/messages/new.html.erb
<h1>Add a news message</h1>
<div class="content">
  <%= simple_form_for @message do |f| %>
    <%= f.input :content, label: 'Short news message:', placeholder: 'Max. 255 characters' %>
    <%= f.button :submit, value: 'Save' %>
  <% end %>
</div>