config/routes.rb
ICAPresents::Application.routes.draw do
  
  resources :home

  resources :sessions

  resources :projects

  resources :messages

  resources :votes

  resources :editions

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/identity/callback', to: 'sessions#create', as: 'admin_signin'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'my_votes', to: 'votes#show', as: 'my_votes'

  root 'home#index'

  

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  has_many :projects, dependent: :restrict_with_error
  validates :name, presence: true
  scope :current, -> { where(current: true) }
  scope :archived, -> { where(current: false) }
  before_save do |record|
    if record.current == true
      Edition.update_all(current: false)
    end
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  respond_to :html, :json
  before_action :check_admin

  def index
    @editions = Edition.all.order(id: :desc)
    respond_with @editions
  end

  def new
    @edition = Edition.new
  end

  def edit
    @edition = Edition.where(id: params[:id]).take
  end

  def create
    @edition = Edition.new(edition_params)
    if @edition.save
      redirect_to editions_path, notice: 'Edition has been created'
    else
      render action: :new
    end
  end

  def update
    @edition = Edition.where(id: params[:id]).take
    if @edition.update(edition_params)
      redirect_to editions_path, notice: 'Edition has been updated'
    else
      render action: :edit
    end
  end

  def destroy
    @edition = Edition.where(id: params[:id]).take
    if @edition.destroy
      redirect_to editions_path, notice: 'Edition has been deleted'
    else
      redirect_to editions_path, notice: 'Edition cannot be deleted'
    end
  end

  private
    def check_admin
      unless admin?
        redirect_to root_url, notice: 'Only administrators have access.'
      end
    end

    def edition_params
      params.require(:edition).permit(:name, :current)
    end

end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/_form.html.erb
<div class="content">
  <%= simple_form_for @edition do |f| %>
    <%= f.input :name, label: 'Name' %>
    <%= f.input :current, label: 'Current?' %>
    <%= f.button :submit, value: 'Save' %>
    <%= link_to 'Cancel', editions_path, class: 'button secondary' %>
    <%= link_to 'Delete', edition_path(@edition), {method: :delete, class: 'button alert', data: {confirm: 'Are you sure?'}} unless @edition.new_record? %>
  <% end %>
</div>

app/views/editions/edit.html.erb
<h1>Edit edtition</h1>
<%= render 'form' %>

app/views/editions/index.html.erb
<%= link_to raw('<span class="icon-plus"></span> New Edition'), new_edition_path, { class: 'button right success' } %>
<h1>Editions </h1>
<div class="content edition-list">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Current</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @editions.each do |e| %>
      <tr>
        <td><%= e.name %></td>
        <td><%= raw(e.current? ? '&#10003;' : '') %></td>
        <td><%= link_to raw('<span class="icon icon-edit"></span> Edit'), edit_edition_path(e), { class: '' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/editions/new.html.erb
<h1>Add new edtition</h1>
<%= render 'form' %>