config/routes.rb
ICAPresents::Application.routes.draw do
  
  resources :home

  resources :sessions

  resources :projects

  resources :messages

  resources :votes

  resources :editions

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/identity/callback', to: 'sessions#create', as: 'admin_signin'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'my_votes', to: 'votes#show', as: 'my_votes'

  root 'home#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :edition
  belongs_to :author, polymorphic: true
  has_many :votes, dependent: :destroy

  validates_presence_of :title, :students, :semester, :location, :time, :description, :picture, message: 'Can not be empty'
  validates_length_of :title, :students, :semester, :location, :time, :picture, maximum: 255, message: 'Can not be longer than 255 characters'

  scope :for_edition, ->(edition) { where(edition_id: edition) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_current_edition, only: [:index, :show, :create, :update]
  before_action :check_logged_in, except: [:index, :show]
  before_action :check_project, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    query = Project.for_edition(params[:edition] || @current_edition)
    if admin?
      if params[:search].present?
        @search = params[:search]
        @projects = query.where('title ILIKE ? OR students ILIKE ? OR semester ILIKE ? OR description ILIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%" , "%#{params[:search]}%").order('created_at DESC')
      else
        @projects = query.order('created_at DESC')
      end
    else
      if params[:search].present?
        @search = params[:search]
        @projects = query.where(approved: true).where('title ILIKE ? OR students ILIKE ? OR semester ILIKE ? OR description ILIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%" , "%#{params[:search]}%").order('created_at DESC')
      else
        @projects = query.where(approved: true).order('title')
      end
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    unless admin?
      unless @project.approved
        redirect_to projects_path, notice: 'Project is not approved yet.'
      end
    end
    @awards = Award.all.order(:id)
  end

  # GET /projects/new
  def new
    unless current_user.try(:admin?)
      @project = Project.new(students: current_user.name)
    else
      @project = Project.new
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.author = current_user
    @project.edition = set_current_edition
    if @project.save
       NewProjectMailer.new_project_email(@project).deliver
      if @project.approved
        redirect_to projects_path, notice: 'Project has been added.'
      else
        redirect_to projects_path, notice: 'Project has been added, but will have to be approved by an administrator.'
      end
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Changes saved.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project has been deleted.'
    else
      redirect_to projects_path, notice: 'Project could not be deleted.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.where(id: params[:id]).first
      unless @project
        redirect_to projects_path, notice: 'Project not found.'
      end
    end

    def set_current_edition
      @current_edition = Edition.current.take
    end

    def check_project
      unless admin?
        if voting_allowed?.call and (params[:action] == 'new' or params[:action] == 'create')
          redirect_to projects_path, notice: 'ICA Presents has started. You can no longer add a project.'
        elsif (params[:action] == 'new' or params[:action] == 'create') and current_user.project.try(:id)
          redirect_to projects_path, notice: 'You have already added a project.'
        elsif (params[:action] == 'edit' or params[:action] == 'update' or params[:action] == 'destroy') and (!current_user.project.try(:id) || current_user.project.try(:id) and current_user.project.try(:id) != @project.id)
          redirect_to projects_path, notice: 'You can only edit or delete your own project.'
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      if admin?
        params[:project].permit(:title, :students, :semester, :location, :time, :description, :picture, :approved, :edition)
      elsif current_user
        params[:project].permit(:title, :students, :semester, :location, :time, :description, :profile, :picture, :edition)
      end
    end
end

app/views/projects/_form.html.erb
<div class="content">
  <%= simple_form_for @project do |f| %>
    <%= f.input :title, label: 'What is the name of this project?', placeholder: 'Project name' %>
    <%= f.input :students, label: 'Which students are involved in this project?', placeholder: 'Your name and the name of your project group members' %>
    <%= select_tag(:semester, options_for_select([['HBO-ICT', "HBO-ICT"], ['CMD', "CMD"], ['Minor', "Minor"], ['Propedeuse', "Propedeuse"]])) %>
    <%= f.input :profile, label: 'What is the profile of the project?', placeholder: 'Enter your profile(s) here if applicable ' %>
    <%= f.input :location, label: 'Where will the project be showcased?', placeholder: 'Example: ICA Lounge or Aula' %>
    <%= f.input :time, label: 'At what time will the project be showcased?', placeholder: 'Example: 14:00 - 16:00' %>
    <%= f.input :description, label: 'Write a short description about the project:', placeholder: 'Project description', input_html: { style: 'height: 200px;' } %>
    <%= f.input :picture, label: 'Paste the URL of a project image:', placeholder: 'Tip: upload your image to imgur.com and paste the URL here', input_html: { type: 'url' } %>
    <% if current_user.try(:admin?) %>
      <%= f.input :approved, label: 'Approved?' %>
    <% elsif current_user.project.try(:id) and !current_user.project.try(:approved) %>
        <p class="white">Your project hasn't been approved by an administrator yet. (<%= Teacher.pluck(:name).join(', ') %>).</p>
    <% end %>
    <%= f.button :submit, value: 'Save' %>
    <% if controller.action_name == 'edit' %>
    <%= link_to 'Delete project', project_path(@project), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: 'button logout' %>
    <% end %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<form action="/projects" method="get">
  <%= hidden_field_tag('edition', params[:edition]) if params[:edition] %>
  <div class="row">
    <div class="large-12 columns search">
      <div class="row collapse">
        <div class="small-10 columns">
          <input type="text" name="search" placeholder="Search for name, student, semester or description">
        </div>
        <div class="small-2 columns">
          <input type="submit" class="button prefix" value="Search" />
        </div>
      </div>
    </div>
  </div>
</form>
<% if current_user and current_user.try(:project) and current_user.project.try(:id) and !current_user.project.try(:approved) %>
<div class="row project-item">
  <p class="top">Your project <strong><%= current_user.project.title %></strong> hasn't been approved by an administrator yet. (<%= Teacher.pluck(:name).join(', ') %>)</p>
</div>
<% end %>
<% if @search.present? %>
<div class="row project-item">
  <p class="top">Search results for: '<%= @search %>' (<%= @projects.length %>).</p>
</div>
<% end %>
<% if @projects.empty? %>
<div class="row project-item">
  <p class="top">No (approved) projects found.</p>
</div>
<% end %>
<% @projects.each do |project| %>
<div class="row project-item">
  <h2><%= project.title %></h2>
  <p class="left">
    <strong>Student(s):</strong> <%= project.students %>
    <br />
    <strong>Semester/minor:</strong> <%= project.semester %>
  </p>
  <div class="no-phone">
    <%= link_to 'More info', project_path(project), class: 'button right no-styling', style: 'width: 50px; margin-right: 50px;' %>
  </div>
  <div class="phone" style="clear: both;">
    <%= link_to 'More info', project_path(project), class: 'button right no-styling', style: 'width: 50px; margin-right: 50px;' %>
  </div>
  <% if admin? %>
    <%= link_to 'Edit', edit_project_path(project), class: 'button right no-styling', style: 'width: 50px; margin-top: 2px;' %>
    <% unless project.approved %>
    <p class="red clear">This project hasn't been approved yet!</p>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/projects/new.html.erb
<h1>Add a project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<div id="votes" class="details">
  <%= image_tag @project.picture %>
  <br /><br />
  <% unless admin? || @project.edition_id != @current_edition.id %>
  <h2>Vote for this project?</h2>
  <% unless current_user %>
  <p class="reminder">You have to be signed in using Facebook to be able to vote.</p>
  <% end %>
  <% @awards.each do |award| %>
    <% if current_user %>
    <% if current_user.votes.pluck(:award_id).include?(award.id) %>
      <% if award.name.match(/tech/i) %>
      <%= link_to raw('<i class="icon-wrench pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, class: 'button disabled expand' %>
      <% elsif award.name.match(/concept/i) %>
      <%= link_to raw('<i class="icon-lightbulb pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, class: 'button disabled expand' %>
      <% elsif award.name.match(/present/i) %>
      <%= link_to raw('<i class="icon-sun pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, class: 'button disabled expand' %>
      <% elsif award.name.match(/audience/i) %>
      <%= link_to raw('<i class="icon-group pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, class: 'button disabled expand' %>
      <% end %>
    <% else %>
      <% if award.name.match(/tech/i) %>
      <%= link_to raw('<i class="icon-wrench pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, data: { confirm: 'Are you sure you want to vote for ' + @project.title  + ' for the award ' + award.name + '?' }, class: 'button expand' %>
      <% elsif award.name.match(/concept/i) %>
      <%= link_to raw('<i class="icon-lightbulb pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, data: { confirm: 'Are you sure you want to vote for ' + @project.title  + ' for the award ' + award.name + '?' }, class: 'button expand' %>
      <% elsif award.name.match(/present/i) %>
      <%= link_to raw('<i class="icon-sun pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, data: { confirm: 'Are you sure you want to vote for ' + @project.title  + ' for the award ' + award.name + '?' }, class: 'button expand' %>
      <% elsif award.name.match(/audience/i) %>
      <%= link_to raw('<i class="icon-group pull-left"></i>' + award.name), votes_path(award_id: award.id, project_id: @project.id), method: :post, data: { confirm: 'Are you sure you want to vote for ' + @project.title  + ' for the award ' + award.name + '?' }, class: 'button expand' %>
      <% end %>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
  <p>
    <strong>Student(s): </strong><%= @project.students %><br />
    <strong>Semester/minor: </strong><%= @project.semester %><br />
    <strong>Location: </strong><%= @project.location %><br />
    <strong>Time: </strong><%= @project.time %>
  </p>
  <p><%= simple_format @project.description %></p>
</div>