config/routes.rb
ICAPresents::Application.routes.draw do
  
  resources :home

  resources :sessions

  resources :projects

  resources :messages

  resources :votes

  resources :editions

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/identity/callback', to: 'sessions#create', as: 'admin_signin'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'my_votes', to: 'votes#show', as: 'my_votes'

  root 'home#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="nl"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="nl"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="nl"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="nl"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "ICA Presents" %></title>
    <%= favicon_link_tag '/favicon.ico' %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class='use-fastclick' data-ica_presents_begins="<%= Home.first.ica_presents_begins.utc.to_i * 1000 %>">
    <div class="background"></div>
    <header>
      <div class="row">
        <%= link_to image_tag('/assets/logo1.png', width: '20%', height: '20%'), '/' %>
        <div class="timer">
          <div class="element">
            <div class="top">Day</div>
            <div id="days">0</div>
          </div>

          <div class="separator">
            <div class="top">&nbsp;</div>
            <div>\</div>
          </div>

          <div class="element">
            <div class="top">Hour</div>
            <div id="hours">0</div>
          </div>

          <div class="separator">
            <div class="top">&nbsp;</div>
            <div>\</div>
          </div>

          <div class="element">
            <div class="top">Min</div>
            <div id="minutes">0</div>
          </div>
        </div>
      </div>
    </header>

    <% if flash[:notice] %>
    <div class="row">
      <div data-alert class="alert-box">
         <%= flash[:notice] %>
      </div>
    </div>
    <% end %>

    <div class="row no-phone">
      <% unless current_user %>
        <%= link_to 'Sign in with Facebook to vote or manage projects', '/auth/facebook', class: 'glyphicon glyphicon-facebook' %>
      <% else %>
        <% if !admin? %>
        <% if current_user.try(:votes) %>
        <%= link_to 'My votes', my_votes_path, class: 'small button logout' %>
        <% end %>
        <% else %>
        <%= link_to 'Edit homepage', edit_home_path(Home.first), class: 'small button logout' %>
        <%= link_to 'Add a news message', new_message_path, class: 'small button logout' %>
        <% end %>
        <% if !admin? and current_user.project %>
        <% if current_user.project.try(:id) %>
        <%= link_to 'Edit your project', edit_project_path(current_user.project), class: 'small button logout' %>
        <% else %>
        <%= link_to 'Add a project', new_project_path, class: 'small button logout' %>
        <% end %>
        <% else %>
        <%= link_to 'Add a project', new_project_path, class: 'small button logout' %>
        <% end %>
        <%= link_to 'Manage editions', editions_path, class: 'small button logout' if admin? %>
        <%= link_to 'Sign out', signout_path, class: 'small button logout' %>
      <% end %>
    </div>

    <div class="row phone">
      <div class="large-12 columns">
      <%= link_to raw('<i class="icon-home pull-left"></i>Home'), '/', class: 'button expand' %>
      <%= link_to raw('<i class="icon-list-alt pull-left"></i>Projects'), projects_path, class: 'button expand' %>
      <% if admin? %>
      <%= link_to raw('<i class="icon-comments pull-left"></i>News messages'), messages_path, class: 'button expand' %>
      <%= link_to raw('<i class="icon-trophy pull-left"></i>Standings'), votes_path, class: 'button expand' %>
      <% end %>
      <% unless current_user %>
        <%= link_to raw('<i class="icon-facebook-sign pull-left"></i>Sign in with Facebook'), '/auth/facebook', class: 'button expand' %>
      <% else %>
        <%= link_to raw('<i class="icon-signout pull-left"></i>Sign out'), signout_path, class: 'button expand' %>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns no-padding">
        <%= yield %>
      </div>
      <div class="large-4 columns menu">
        <div class="no-phone">
        <%= link_to raw('<i class="icon-home pull-left"></i>Home'), '/', class: 'button expand' %>
        <%= link_to raw('<i class="icon-list-alt pull-left"></i>Projects'), projects_path, class: 'button expand' %>
        <%= link_to raw('<i class="icon-archive pull-left"></i>Archives'), "#", class: 'button expand dropdown archives', data: {dropdown:'archived-editions'} %>
        <% if admin? %>
        <%= link_to raw('<i class="icon-comments pull-left"></i>News messages'), messages_path, class: 'button expand' %>
        <%= link_to raw('<i class="icon-trophy pull-left"></i>Standings'), votes_path, class: 'button expand' %>
        <% end %>
        <ul id="archived-editions" class="f-dropdown" data-dropdown-content>
        <% @archived_editions.each do |ae| %>
            <li><%= link_to ae.name, projects_path(edition: ae.id) %></li>
        <% end %>
        </ul>
        </div>
        <a class="twitter-timeline"  href="https://twitter.com/search?q=%23icapresents"  data-widget-id="348142153492475904">Tweets over "#icapresents"</a>
        <div class="image-box">
          <%= image_tag '/assets/logo2.png' %>
        </div>
        <div class="form-box">
          <% unless current_user %>
          <%= form_tag admin_signin_path, autocomplete: 'off' do %>
            <h4>Jury sign in</h4>
            <div class="field">
              <%= email_field_tag :auth_key, nil, placeholder: 'E-mail' %>
            </div>
            <div class="field">
              <%= password_field_tag :password, nil, placeholder: 'Password' %>
            </div>
            <div class="actions"><%= submit_tag "Sign in", class: 'small button' %></div>
          <% end %>
          <% else %>
          <h4>Sign out</h4>
          <p><%= current_user.name %></p>
          <div class="actions"><%= link_to 'Sign out', signout_path, class: 'small button' %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row phone">
      <div class="large-12 columns">
        <% if current_user %>
          <% if !admin? %>
            <% if current_user.try(:votes) %>
              <%= link_to 'My votes', my_votes_path, class: 'button expand' %>
            <% end %>
          <% else %>
            <%= link_to 'Edit homepage', edit_home_path(Home.first), class: 'button expand' %>
              <%= link_to 'Add a news message', new_message_path, class: 'button expand' %>
          <% end %>
          <% if !admin? %>
            <% if current_user.project.try(:id) %>
              <%= link_to 'Edit your project', edit_project_path(current_user.project), class: 'button expand' %>
            <% else %>
              <%= link_to 'Add a project', new_project_path, class: 'button expand' %>
            <% end %>
          <% else %>
            <%= link_to 'Add a project', new_project_path, class: 'button expand' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>